<?php

use App\Layouts\TabsLayout;
use App\NativeComponents\CreateInventoryItem;
use App\NativeComponents\CreateList;
use App\NativeComponents\CreateRecipe;
use App\NativeComponents\CreateRoutine;
use App\NativeComponents\Dashboard;
use App\NativeComponents\EditInventoryItem;
use App\NativeComponents\EditList;
use App\NativeComponents\EditRecipe;
use App\NativeComponents\EditRoutine;
use App\NativeComponents\Home;
use App\NativeComponents\Inventory;
use App\NativeComponents\InventoryItemDetail;
use App\NativeComponents\InventoryItemQrCode;
use App\NativeComponents\ListDetail;
use App\NativeComponents\Lists;
use App\NativeComponents\Login;
use App\NativeComponents\OpenItemLink;
use App\NativeComponents\RecipeDetail;
use App\NativeComponents\Recipes;
use App\NativeComponents\Register;
use App\NativeComponents\RoutineDetail;
use App\NativeComponents\Routines;
use App\NativeComponents\ScanInventory;
use App\NativeComponents\Today;
use Illuminate\Support\Facades\Route;

Route::native('/', Home::class);
Route::native('/login', Login::class);
Route::native('/register', Register::class);
Route::nativeGroup(TabsLayout::class, function () {
    Route::native('/dashboard', Dashboard::class);
    Route::native('/today', Today::class);
    Route::native('/routines', Routines::class);
    Route::native('/routines/create', CreateRoutine::class);
    Route::native('/routines/{id}', RoutineDetail::class);
    Route::native('/routines/{id}/edit', EditRoutine::class);
    Route::native('/recipes', Recipes::class);
    Route::native('/recipes/create', CreateRecipe::class);
    Route::native('/recipes/{id}', RecipeDetail::class);
    Route::native('/recipes/{id}/edit', EditRecipe::class);
    Route::native('/inventory', Inventory::class);
    Route::native('/inventory/create', CreateInventoryItem::class);
    Route::native('/inventory/scan', ScanInventory::class);
    Route::native('/inventory/{id}', InventoryItemDetail::class);
    Route::native('/inventory/{id}/edit', EditInventoryItem::class);
    Route::native('/inventory/{id}/qr-code', InventoryItemQrCode::class);
    Route::native('/i/{id}', OpenItemLink::class);
    Route::native('/lists', Lists::class);
    Route::native('/lists/create', CreateList::class);
    Route::native('/lists/{id}', ListDetail::class);
    Route::native('/lists/{id}/edit', EditList::class);
});
